#!/usr/bin/env python3
#
# Copyright (C) 2026 ETH Zurich and University of Bologna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

"""Generate the InSitu-cache calibration trace suite.

Emits `port,rw,addr,size,delay` trace files (shared stimulus format,
TRACE_SPEC.md §3) into ``traces/``. These reproduce the RTL calibration
testbench's metric phases so the GVSoC per-access CSVs can be diffed against the
RTL ``REPORT.md`` / ``results_memlat*.csv`` reference numbers.

The traces are pure stimulus (no timing) — identical for both engines. Run:

    python3 pulp/insitu_cache_calib/gen_traces.py
    INSITU_CALIB_TRACE=cold_miss_isolated gvsoc --target=insitu_cache_calib run
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
TRACES = os.path.join(HERE, 'traces')

BASE = 0x8000_0000      # DRAM space, matches RTL traces
LINE = 64               # cache line bytes (512b)
WORD = 4                # tcdm word bytes
CAP_LINES = 1024        # calib DUT capacity: 4 ways × 256 sets (= 64 KiB)


def w(name, lines):
    os.makedirs(TRACES, exist_ok=True)
    path = os.path.join(TRACES, name + '.trace')
    with open(path, 'w') as f:
        f.write(f'# {name} — generated by gen_traces.py\n')
        f.write('# port,rw,addr,size,delay\n')
        for ln in lines:
            f.write(ln + '\n')
    print(f'wrote {path} ({len(lines)} accesses)')


def main():
    # 1. Isolated warm read-hit: one cold preload, long idle so the refill lands,
    #    then a re-read of the same word — its latency is the warm-hit latency.
    #    (RTL ref: 10 cyc, MemLatency-independent.)
    w('warm_hit_isolated', [
        f'0,R,0x{BASE:08x},4,0',
        f'0,R,0x{BASE:08x},4,600',     # idle > worst-case refill so the line is resident
    ])

    # 2. Isolated cold read-miss: a single cold read. Latency = MemLatency + 17 (RTL).
    w('cold_miss_isolated', [
        f'0,R,0x{BASE:08x},4,0',
    ])

    # 3. Cold-miss stream, 1 port: 64 distinct lines, back-to-back. Exercises refill
    #    serialization → throughput ≈ 1/(MemLatency+17). (RTL: 64 acc / 3530 cyc @ ML50.)
    w('cold_stream_1p', [f'0,R,0x{BASE + i*LINE:08x},4,0' for i in range(64)])

    # 3b. Long cold-miss stream (512 distinct lines). In the wide-refill experiment config
    #     (INSITU_CALIB_WIDE_REFILL=1) this approaches the sustained plateau set by the
    #     32-outstanding requester budget (Little's law: ~32/(MemLatency+13) ≈ 0.5 @ML50),
    #     past the fill/drain transient of the 64-line burst. (THROUGHPUT_EXPERIMENT.md §3.)
    w('cold_stream_long', [f'0,R,0x{BASE + i*LINE:08x},4,0' for i in range(512)])

    # 4. Warm-hit stream, 1 port: preload 16 lines (cold), idle to let them land, then
    #    stream 64 re-reads (4 reads per line) — all hits. Measures the hit-throughput
    #    ceiling (RTL: 0.86 acc/cyc single-port). Preload + measured are one trace; the
    #    preload misses are folded into the aggregate, so read the per-access tail for
    #    the steady-state hit latency (RTL streaming hit = 7 cyc).
    NSET = 16
    lines = [f'0,R,0x{BASE + i*LINE:08x},4,0' for i in range(NSET)]   # cold preload
    # idle gap on the port so all refills land before the hit stream
    lines.append(f'0,R,0x{BASE:08x},4,1500')
    for r in range(64):
        i = r % NSET
        lines.append(f'0,R,0x{BASE + i*LINE:08x},4,0')
    w('warm_stream_1p', lines)

    # 5. Warm-hit stream, 4 ports: 4 VLSU ports each stream hits over their OWN disjoint
    #    16-line region (so no port depends on another's preload). Each port: 16 cold
    #    preloads + idle (so its refills land) + 64 hits. Run concurrently → measures
    #    multi-port hit scaling on the shared controller (RTL: ≈0.86, strongly
    #    sub-linear). Throughput is computed from accesses issued after the warmup window
    #    (t_issue ≥ 1600) — see the analysis post-step in the calib report.
    NSET = 16
    PORT_STRIDE = 0x10000          # disjoint per-port region
    lines = []
    for p in range(4):
        rgn = BASE + p * PORT_STRIDE
        for i in range(NSET):                                 # cold preload (this port)
            lines.append(f'{p},R,0x{rgn + i*LINE:08x},4,0')
        lines.append(f'{p},R,0x{rgn:08x},4,4000')             # idle so refills land
        for r in range(64):                                   # hit stream (this port)
            i = r % NSET
            lines.append(f'{p},R,0x{rgn + i*LINE:08x},4,0')
    w('warm_stream_4p', lines)

    # 5b. Hit-pipeline injection-gap sweep (RTL bw_hit_gap{0,1,3,7}, single port, all hits).
    #     Preload 16 lines resident, idle, then 64 hits each issued `gap` idle cycles after
    #     the previous. RTL: the steady-state hit latency rises with the gap as the three
    #     decoupling registers drain — gap0→7/7/10, gap1→8/8/10, gap3→10/10/10, gap7→10.
    #     This is the verification of the streaming-hit warmth gradient. Read the tail (drop
    #     the first/pipeline-fill access) for the steady-state per-access latency.
    NSET = 16
    for gap in (0, 1, 2, 3, 7):
        lines = [f'0,R,0x{BASE + i*LINE:08x},4,0' for i in range(NSET)]   # cold preload
        lines.append(f'0,R,0x{BASE:08x},4,1500')                          # idle so refills land
        for r in range(64):
            i = r % NSET
            lines.append(f'0,R,0x{BASE + i*LINE:08x},4,{gap}')
        w(f'bw_hit_gap{gap}', lines)

    # ---- New phases mirroring the RTL TB (CHARACTERIZATION.md, 2026-06-01) ----

    # 6. Isolated warm WRITE: preload a line resident, idle, then write it.
    #    (RTL warm_write_latency: 8 cyc, MemLatency-independent.)
    w('warm_write_isolated', [
        f'0,R,0x{BASE:08x},4,0',
        f'0,W,0x{BASE:08x},4,600',
    ])

    # 7. Warm WRITE stream, 1 port: preload 16 lines, idle, 64 writes to the
    #    resident region. (RTL warm_write_thrupt_1p: 0.489 acc/cyc ≈ ½ read.)
    NSET = 16
    lines = [f'0,R,0x{BASE + i*LINE:08x},4,0' for i in range(NSET)]
    lines.append(f'0,R,0x{BASE:08x},4,1500')
    for r in range(64):
        lines.append(f'0,W,0x{BASE + (r % NSET)*LINE:08x},4,0')
    w('warm_write_stream_1p', lines)

    # 8. Read-after-write, SAME word: preload resident, idle, write the word, then
    #    immediately read it back. The RTL forwarding buffer serves the read with
    #    no memory access (RTL raw_same_word: 7 cyc, mem_rd=0, MemLatency-indep).
    w('raw_same_word', [
        f'0,R,0x{BASE:08x},4,0',       # make line resident
        f'0,W,0x{BASE:08x},4,600',     # warm write to the word
        f'0,R,0x{BASE:08x},4,0',       # read-after-write, same word (measured)
    ])

    # 9. Coalesced COLD, 4 ports: all 4 VLSU ports read the SAME line on (near) the
    #    same cycle, each a distinct word, across 32 fresh lines. RTL: the input
    #    par_coalescer merges them to 1 miss/line → mem_rd=32. The GVSoC model has
    #    no input coalescer, but the controller's MSHR merges secondary misses to a
    #    READ_PEND line → also 1 refill/line → mem_rd should land at 32.
    #    NOTE: this trace is intentionally READ-ONLY into a fresh region, so on GVSoC every
    #    miss lands in an INVALID way and there are NO dirty victims → mem_wr=0. The RTL
    #    coal_cold reports mem_wr=32 only because its SHARED testbench pre-dirtied these sets
    #    in earlier phases — a TB-history artifact, not cache behaviour. Do NOT "fix" the
    #    mem_wr divergence by pre-dirtying here: doing so double-reserves the install pipe
    #    (eviction+refill ≈9 cyc/line) and UNDERSHOOTS to ~0.31 thr / 169 lat. See
    #    prompt/insitu_cache_calib_report.md §13.
    ITERS = 32
    rgn = BASE + 0x40000
    lines = []
    for it in range(ITERS):
        for p in range(4):
            lines.append(f'{p},R,0x{rgn + it*LINE + p*WORD:08x},4,0')
    w('coal_cold_4port', lines)

    # 10. Coalesced WARM, 4 ports: same as cold but the 32 lines are preloaded
    #     resident first, so every coalesced read hits. RTL: 3.28 acc/cyc, mem_rd=0.
    #     The preload is issued on the SCALAR port (port 4), NOT a VLSU port, so all
    #     four VLSU ports (0..3) enter the measured phase with no per-port preload
    #     offset — they stay cycle-aligned, which is what lets the interco coalescer
    #     merge all 4 same-line reads each cycle (port-0 preload used to lag port 0
    #     by ~32 cyc, collapsing the merge to 3 ports).
    rgn = BASE + 0x50000
    lines = [f'4,R,0x{rgn + it*LINE:08x},4,0' for it in range(ITERS)]   # preload via scalar port
    # the VLSU ports have no preload; push every measured port's first read past the
    # preload drain (~ITERS × (ML+overhead)) so all 32 lines are resident.
    WARMUP = 2500
    for it in range(ITERS):
        for p in range(4):
            delay = WARMUP if it == 0 else 0
            lines.append(f'{p},R,0x{rgn + it*LINE + p*WORD:08x},4,{delay}')
    w('coal_warm_4port', lines)

    # 11. Eviction — dirty fill: write a 2× capacity span so the second half evicts
    #     dirty victims from the first half (RTL evict_dirty_fill: mem_wr ≈ ½ misses).
    rgn = BASE + 0x100000
    w('evict_dirty_fill',
      [f'0,W,0x{rgn + i*LINE:08x},4,0' for i in range(2 * CAP_LINES)])

    # 12. Eviction — writeback-miss stream: fill capacity dirty (writes), then read a
    #     fresh capacity-sized span so every read miss evicts a still-dirty victim
    #     (RTL evict_wb_miss_stream: writeback adds ~+10% miss latency).
    rgn_w = BASE + 0x300000
    rgn_r = BASE + 0x500000
    lines = [f'0,W,0x{rgn_w + i*LINE:08x},4,0' for i in range(CAP_LINES)]
    lines += [f'0,R,0x{rgn_r + i*LINE:08x},4,0' for i in range(CAP_LINES)]
    w('evict_wb_miss_stream', lines)


if __name__ == '__main__':
    main()
